name: Moulinette CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Moulinette
      run: curl https://raw.githubusercontent.com/42pde-bakk/push_swap/master/moulinette.sh > moulinette.sh
    - name: Get checker
      run: curl https://projects.intra.42.fr/uploads/document/document/8292/checker_linux
    - name: Run_script
      run: bash moulinette.sh
